name: dev
channels:
  - defaults
dependencies:
  - python=3.11.5
  - scikit-learn=1.5.1
  - scipy=1.13.1
  - seaborn=0.13.2
  - statsmodels=0.14.2
  - ydata-profiling=4.8.3
  - black=24.4.2
  - bokeh=3.4.1
  - Jupyter=1.0.0
  - numpy=1.26.4
  - pandas=2.2.2
  - pip=24.0
  - matplotlib=3.8.4
  - requests=2.32.3